services:
  vehicle-test-db:
    image: mysql:latest
    container_name: vehicle-test-db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql:test
      MYSQL_DATABASE: vehicles

  vehicle-db:
    image: mysql:latest
    container_name: vehicle-db
    environment:
      MYSQL_ROOT_PASSWORD: mysql:1.0
      MYSQL_DATABASE: vehicles

  vehicle-service:
    image: seke.bi/vehicle-service:1.0
    links:
      - vehicle-db
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: prod


  # Delivery Service
  delivery-cassandra-test:
    image: cassandra:latest
    container_name: delivery-cassandra-test
    ports:
      - 9042:9042

  delivery-redis-test:
    image: redis/redis-stack:latest
    container_name: delivery-redis-test
    ports:
      - 6379:6379
      - 8001:8001

  pl-kafka-broker:
    image: bitnami/kafka:latest
    container_name: pl-kafka-broker
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

