#networks:
#  delivery-network:
#    name: delivery-network
#    external: true
services:
  #  vehicle-test-db:
  #    image: mysql:latest
  #    container_name: vehicle-test-db
  #    ports:
  #      - 3307:3306
  #    environment:
  #      MYSQL_ROOT_PASSWORD: mysql:test
  #      MYSQL_DATABASE: vehicles
  #
  #  vehicle-db:
  #    image: mysql:latest
  #    container_name: vehicle-db
  #    environment:
  #      MYSQL_ROOT_PASSWORD: mysql:1.0
  #      MYSQL_DATABASE: vehicles
  delivery-service:
    image: seke.bi/delivery-service:1.0
    container_name: delivery-service
    links:
      - delivery-cassandra-test
      - delivery-redis-test
      - pl-kafka-broker-0
    ports:
      - 8090:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod

  pricing-service:
    image: seke.bi/pricing-service:1.0
    container_name: pricing-service
    ports:
      - 8091:8080
    links:
      - delivery-cassandra-test
      - delivery-redis-test
      - pl-kafka-broker-0
    environment:
      SPRING_PROFILES_ACTIVE: prod

  payment-service:
    image: seke.bi/payment-service:1.0
    container_name: payment-service
    links:
      - mongo-test
    ports:
      - 8092:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod


  delivery-cassandra-test:
    image: cassandra:latest
    container_name: delivery-cassandra-test
    ports:
      - 9042:9042

  delivery-redis-test:
    image: redis/redis-stack:latest
    container_name: delivery-redis-test
    ports:
      - 6379:6379
      - 8001:8001

  pl-kafka-broker-0:
    image: bitnami/kafka:latest
    container_name: pl-kafka-broker-0
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

  mongo-test:
    image: mongo:latest
    container_name: mongo-test
    ports:
      - 27017:27017
