logging.level:
  bi.: DEBUG
spring:
  application.name: Payment-service
  mvc.servlet.path: /payment
  task:
    scheduling:
      pool.size: 1

  data:
    mongodb:
      database: payment_1_0
      host: localhost
      port: 27017
  kafka:
    bootstrap-servers: localhost:9092
    admin.auto-create: true
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      properties:
        spring.json.trusted.packages: bi.seke.schema
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      group-id: ${spring.application.name}
      properties:
        spring.json.trusted.packages: bi.seke.schema

config:
  pricing-topic-name: PricingTopic
  paid-topic-name: PaidTopic
  cancel-topic-name: CancelTopic
  paid-topic-clean-policy: compact,delete
  price-mismatch-retries: 1
  price-mismatch-retry-delay: 1
  price-mismatch-return: false
  payment-confirmation-statuses:
    0: ACCEPTED
    -1: PAYED_LESS
    1: OVERCHARGED
  accepted-confirmation-statuses:
    - ACCEPTED
    - OVERCHARGED
