server.port: 8089
spring:
  application.name: Delivery-Service
  profiles.include: sampledata
  mvc.servlet.path: /deliveries

  cassandra:
    schema-action: recreate
    local-datacenter: datacenter1
    keyspace-name: delivery_1_0

    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    contact-points:
      - localhost

  data.redis:
    host: localhost
    port: 6379
  cache:
    redis.time-to-live: 360000
    cache-names: Packages, DeliveryTypes
    type: redis

  kafka:
    bootstrap-servers: localhost:9092
    admin.auto-create: true

config:
  date-format: dd-MM-yyyy
